# This is a workflow to build and release a package using pnpm and node18 on ubuntu20.04

name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds and releases the package
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Installs pnpm using curl
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

      # Installs node18 using nvm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Install dependencies
        run: pnpm install

      # Builds the package using pnpm
      - name: Build package
        run: pnpm build

      # Creates a release using ncipollo/release-action
      - name: Github Release
        uses: elgohr/Github-Release-Action@v4
        with:
          body: |
            ${{ steps.release-notes.outputs.notes }}
          tag_name: ${{ steps.release-notes.outputs.version }}
          release_name: ${{ steps.release-notes.outputs.version }}
          files: |
            .output/*
          draft: false
          prerelease: false
